[View in Colaboratory](https://colab.research.google.com/github/kalyan369/Python_Practice/blob/master/AA_Numpy_Examples.ipynb)

In [0]:
import numpy as np

In [0]:
a = [1,2,3,4]
b = [11,12,23,14]

In [14]:
a + b # + is a concatenation in python. so it will not hlp in element wise addition of elements in two lists

[1, 2, 3, 4, 11, 12, 23, 14]

In [0]:
output = []

In [16]:
# for doing elementwise addition of elements of items in two lists
for item1,item2 in zip(a,b):
  output.append(item1+item2)
 
print(output)

[12, 14, 26, 18]


In [0]:
# Below is the snipet for time benefit that you get in using numpy

In [0]:
g=list(range(1000000))

In [19]:
%timeit sum(g)

100 loops, best of 3: 8.97 ms per loop


In [0]:
# above time of very slow when compared to what a machine can perform

In [0]:
g_array = np.array(g)

In [22]:
%timeit np.sum(g_array)

The slowest run took 6.13 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 859 µs per loop


In [0]:
# that is the benefit one get using numpy

In [24]:
a

[1, 2, 3, 4]

In [0]:
# numpy puts all the elements into one data structure and one data type, finally into one memory buffer unlike python list

In [0]:
a = np.array([1,2,3,4]) # putting a list in numpy array construtor

In [0]:
b = np.array([10,11,12,13])

In [29]:
a

array([1, 2, 3, 4])

In [30]:
b

array([10, 11, 12, 13])

In [31]:
a+b # numpy array elemetwise additiona

array([11, 13, 15, 17])

In [32]:
a - b

array([-9, -9, -9, -9])

In [33]:
a * b

array([10, 22, 36, 52])

In [34]:
a / b

array([0.1       , 0.18181818, 0.25      , 0.30769231])

In [35]:
a ** b

array([       1,     2048,   531441, 67108864])