[View in Colaboratory](https://colab.research.google.com/github/kalyan369/Python_Practice/blob/master/AA_Numpy_Examples.ipynb)

In [0]:
import numpy as np

In [0]:
a = [1,2,3,4]
b = [11,12,23,14]

In [64]:
a + b # + is a concatenation in python. so it will not hlp in element wise addition of elements in two lists

[1, 2, 3, 4, 11, 12, 23, 14]

In [0]:
output = []

In [66]:
# for doing elementwise addition of elements of items in two lists
for item1,item2 in zip(a,b):
  output.append(item1+item2)
 
print(output)

[12, 14, 26, 18]


In [0]:
# Below is the snipet for time benefit that you get in using numpy

In [0]:
g=list(range(1000000))

In [69]:
%timeit sum(g)

100 loops, best of 3: 8.87 ms per loop


In [0]:
# above time of very slow when compared to what a machine can perform

In [0]:
g_array = np.array(g)

In [72]:
%timeit np.sum(g_array)

1000 loops, best of 3: 843 µs per loop


In [0]:
# that is the benefit one get using numpy

In [74]:
a

[1, 2, 3, 4]

In [0]:
# numpy puts all the elements into one data structure and one data type, finally into one memory buffer unlike python list

In [0]:
a = np.array([1,2,3,4]) # putting a list in numpy array construtor

In [0]:
b = np.array([10,11,12,13])

In [78]:
a

array([1, 2, 3, 4])

In [79]:
b

array([10, 11, 12, 13])

In [80]:
a+b # numpy array elemetwise additiona

array([11, 13, 15, 17])

In [81]:
a - b

array([-9, -9, -9, -9])

In [82]:
a * b

array([10, 22, 36, 52])

In [83]:
a / b

array([0.1       , 0.18181818, 0.25      , 0.30769231])

In [84]:
a ** b

array([       1,     2048,   531441, 67108864])

In [85]:
type(a) # checking the type

numpy.ndarray

In [86]:
a.dtype # Numeric type of the elements.every element is of same type

dtype('int64')

In [87]:
a.ndim #number of dimensions

1

In [88]:
a.shape  #array shape

(4,)

In [89]:
a.itemsize #bytes per element

8

In [90]:
a.nbytes # total number of bytes of memory used

32

In [0]:
f =9

In [92]:
type(f)

int

In [0]:
f = (5,6) #a number with tailing comma is a tuple. It is not bracket that makes a tuple rather its comma that makes a tuple

In [94]:
type(f)

tuple

In [95]:
(10)

10

In [96]:
10,

(10,)

In [97]:
type(a.shape)

tuple

In [98]:
a

array([1, 2, 3, 4])

In [99]:
b

array([10, 11, 12, 13])

In [100]:
a * 10 #This is called broadcasting

array([10, 20, 30, 40])

In [101]:
a * 100

array([100, 200, 300, 400])

In [102]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [103]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [104]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [106]:
np.log #These are universal universal functions

<ufunc 'log'>

In [107]:
np.sum

<function numpy.core.fromnumeric.sum>

In [108]:
sum

<function sum>

In [0]:
# numpy array elements are mutable which means able to change the elements