[View in Colaboratory](https://colab.research.google.com/github/kalyan369/Python_Practice/blob/master/AA_Numpy_Examples.ipynb)

In [0]:
import numpy as np

In [0]:
a = [1,2,3,4]
b = [11,12,23,14]

In [3]:
a + b # + is a concatenation in python. so it will not hlp in element wise addition of elements in two lists

[1, 2, 3, 4, 11, 12, 23, 14]

In [0]:
output = []

In [5]:
# for doing elementwise addition of elements of items in two lists
for item1,item2 in zip(a,b):
  output.append(item1+item2)
 
print(output)

[12, 14, 26, 18]


In [0]:
# Below is the snipet for time benefit that you get in using numpy

In [0]:
g=list(range(1000000))

In [8]:
%timeit sum(g)

100 loops, best of 3: 9.14 ms per loop


In [0]:
# above time of very slow when compared to what a machine can perform

In [0]:
g_array = np.array(g)

In [11]:
%timeit np.sum(g_array)

1000 loops, best of 3: 1.1 ms per loop


In [0]:
# that is the benefit one get using numpy

In [13]:
a

[1, 2, 3, 4]

In [0]:
# numpy puts all the elements into one data structure and one data type, finally into one memory buffer unlike python list

In [0]:
a = np.array([1,2,3,4]) # putting a list in numpy array construtor

In [0]:
b = np.array([10,11,12,13])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
b

array([10, 11, 12, 13])

In [19]:
a+b # numpy array elemetwise additiona

array([11, 13, 15, 17])

In [20]:
a - b

array([-9, -9, -9, -9])

In [21]:
a * b

array([10, 22, 36, 52])

In [22]:
a / b

array([0.1       , 0.18181818, 0.25      , 0.30769231])

In [23]:
a ** b

array([       1,     2048,   531441, 67108864])

In [24]:
type(a) # checking the type

numpy.ndarray

In [25]:
a.dtype # Numeric type of the elements.every element is of same type

dtype('int64')

In [26]:
a.ndim #number of dimensions

1

In [27]:
a.shape  #array shape

(4,)

In [28]:
a.itemsize #bytes per element

8

In [29]:
a.nbytes # total number of bytes of memory used

32

In [0]:
f =9

In [31]:
type(f)

int

In [0]:
f = (5,6) #a number with tailing comma is a tuple. It is not bracket that makes a tuple rather its comma that makes a tuple

In [33]:
type(f)

tuple

In [34]:
(10)

10

In [35]:
10,

(10,)

In [36]:
type(a.shape)

tuple

In [37]:
a

array([1, 2, 3, 4])

In [38]:
b

array([10, 11, 12, 13])

In [39]:
a * 10 #This is called broadcasting

array([10, 20, 30, 40])

In [40]:
a * 100

array([100, 200, 300, 400])

In [41]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [42]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [43]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [44]:
np.log #These are universal universal functions

<ufunc 'log'>

In [45]:
np.sum

<function numpy.core.fromnumeric.sum>

In [46]:
sum

<function sum>

In [0]:
# numpy array elements are mutable which means able to change the elements

In [48]:
a[0]

1

In [49]:
a

array([1, 2, 3, 4])

In [0]:
a[0]=10

In [51]:
a

array([10,  2,  3,  4])

In [52]:
a.dtype

dtype('int64')

In [0]:
a[0]= 10.6

In [54]:
a

array([10,  2,  3,  4])

In [0]:
# assigning a float into an int array truncates the decimal part

In [0]:
# fill has the same behavior

In [0]:
a.fill(-9.3)

In [58]:
a

array([-9, -9, -9, -9])

In [0]:
# Good as it predictable. Bad as it not flexible

In [0]:
a = np.array([1,2,3,4])

In [61]:
a.dtype

dtype('int64')

In [0]:
a = np.array([1,2,3.9,4])

In [63]:
a.dtype

dtype('float64')

In [0]:
a = np.array([1,2,3.9,4.0+67j])

In [65]:
a.dtype

dtype('complex128')

In [0]:
# Type of array elements will be based on elements. Hierarchy pf datatypes is followed


In [0]:
a = np.array([1,2,3,4],dtype='int32')  # to enforce a type elemets in numpy array use the attribute dtype

In [67]:
a.dtype

dtype('int32')

In [68]:
a

array([1, 2, 3, 4], dtype=int32)

In [0]:
c = np.array([[10,11,12],[20,21,22]])

In [71]:
c

array([[10, 11, 12],
       [20, 21, 22]])

In [72]:
c.dtype

dtype('int64')

In [73]:
c.ndim

2

In [74]:
c.shape

(2, 3)

In [75]:
a.shape

(4,)

In [0]:
#Dont use numpy matrix module as it is going to be depreciated

In [77]:
c.size

6

In [78]:
c

array([[10, 11, 12],
       [20, 21, 22]])

In [80]:
c.nbytes # Tells you the amount of memory the data portion is taking

48

In [81]:
a

array([1, 2, 3, 4], dtype=int32)

In [82]:
a[1]

2

In [85]:
c[0,0] # Unlike the python list where it is written as c[0][0]-ALSO WHEN U R CHANGING VALUE OF ANY DIMENSION PUT THE VALUES IN SAME SQUARE BRACKETS

10

In [87]:
c[0] # returns entire row if the array is two dimensional

array([10, 11, 12])