[View in Colaboratory](https://colab.research.google.com/github/kalyan369/Python_Practice/blob/master/AB_Numpy_Examples_Multi_Dimensional_Arrays.ipynb)

In [0]:
import numpy as np

In [0]:
# RULES OF COMPUTATIONS WITH ARRAYS

# Rule 1: Operations btween multiple array objects are first checked for proper shape match

# Rule 2: Mathematical operators(+,-,*,/,exp,log,..) apply element by element, on the values

# Rule 3: Reduction operation(mean,std,skew,kurt,sum,prod,..) apply to the whole array, unless an axis is specified

# Rule 4: Missing values propagate unless explicitly ignored (nanmean,nansum,..)

In [3]:
np.nan + 6

nan

In [4]:
np.sum([1,np.nan,9])

nan

In [0]:
a=np.arange(25).reshape(5,5)

In [7]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
a[a%3 == 0].sum() # Sums all the ememnts divisble by 3

108

In [0]:
# ARRAY CALCULATION METHOD 

In [0]:
a = np.array([1,2,3])

In [12]:
a

array([1, 2, 3])

In [13]:
np.sum(a)

6

In [14]:
a.sum()

6

In [0]:
#Method act on data stored in the array
a = np.array([[1,2,3],
            [4,5,6]])

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# .sum() defaults to adding up all the values in a array
a.sum()

21

In [25]:
#supply the keyword axis to sum along the last axis 
a.sum(axis=0) # axis can also be -2

array([5, 7, 9])

In [26]:
a.sum(axis=1) # axis can also ne -1

array([ 6, 15])

In [0]:
# Intutition behind doing sum over axis=0 on (2,3) matrix is that 2 becomes zero and result will be (3,)
# postive and negative axis for (3,4,5) matrix is 0,1,2 and -3,-2,-1 respectively

In [0]:
a = np.arange(24).reshape(6,4)

In [29]:
a.shape

(6, 4)

In [30]:
a.mean(axis=0).shape

(4,)

In [31]:
a.mean(axis=1).shape

(6,)

In [0]:
channels_means = a.mean(axis=1)

In [0]:
#MIN

In [0]:
a = np.array([2.,3.,0.,1.])

In [35]:
a.min(axis=0)

0.0

In [0]:
#Use Numpy's min() instead of python's built-in min() for speedy operations on multi-dimensional arrays.

In [37]:
np.min(a,axis=0)

0.0

In [38]:
np.max(a,axis=0)

3.0

In [0]:
#ARGMIN

In [40]:
np.argmin(a,axis=0)

2

In [0]:
#ARGMAX

In [42]:
np.argmax(a,axis=0)

1