[View in Colaboratory](https://colab.research.google.com/github/kalyan369/Python_Practice/blob/master/AB_Numpy_Examples_Fancy_Indexing.ipynb)

In [0]:
import numpy as np

In [27]:
a = np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [0]:
#Fancy indexing
indices = [1,2,-3]
y = a[indices]

In [29]:
y

array([10, 20, 50])

In [0]:
# Manual creation of masks
mask = np.array([0,1,1,0,0,1,0,1],dtype=bool) # numpy converts all 1s into True and 0s into False

In [0]:
# Conditional creation of masks
mask2 = a < 30

In [32]:
# fancy indexing
y = a[mask]
print(y)

[10 20 50 70]


In [33]:
# Applying mask2 on the numpy array
y = a[mask2]
y

array([ 0, 10, 20])

In [0]:
a = np.array([3,-1,-2,4,-6,8])

In [35]:
a < 0

array([False,  True,  True, False,  True, False])

In [0]:
negatives = a < 0

In [37]:
a[negatives] # returns all the negative values in the array

array([-1, -2, -6])

In [38]:
a[a<0] 

array([-1, -2, -6])

In [0]:
a[a<0] = 0 # assign 0 to all the negative values

In [40]:
a

array([3, 0, 0, 4, 0, 8])

In [41]:
a < 8

array([ True,  True,  True,  True,  True, False])

In [42]:
a >3

array([False, False, False,  True, False,  True])

In [0]:
# a > 3 and a < 8

In [44]:
(a<8).any() # returns true even if one of them is false

True

In [0]:
# & stands for and , | stands for or, ~ stands for not, and ^ stands for xor

In [0]:
# Binary operators (and, or,not) needs one true and one false each side

In [0]:
# Bitwise operators & (and) , | (or), ~ (not), ^ (xor)

In [0]:
# Biwise operators are for element wise operation

In [49]:
(a > 3) & (a < 8) # Brackets are used as bitwise operators has higher precedence over comparison operators

array([False, False, False,  True, False, False])

In [50]:
a

array([3, 0, 0, 4, 0, 8])

In [0]:
f=6
g=9

In [52]:
f+g

15

In [53]:
f.__add__(g) # __add__ is calld dunder similar to that athere are a.__abs__, a.__add__

15

In [0]:
#   OR TABLE
#   T  |  F
#T  T     F
#F  T     F
#

In [0]:
#   XOR TABLE
#   T  |  F
#T  F     T
#F  T     F
#

In [57]:
a[(a > 3) & (a < 8)] # Filtering data

array([4])

In [0]:
# Whenver we slice the array, we get a view. View of the same memory buffer. 

In [0]:
# Everytime you do fancy indexing you get a copy of array..that is real difference 

In [61]:
np.nonzero(negatives) # to get the positions of True in the mask

(array([1, 2, 4]),)

In [62]:
a

array([3, 0, 0, 4, 0, 8])

In [0]:
a.sort() # sorting the array

In [66]:
a

array([0, 0, 0, 3, 4, 8])

In [0]:
a=np.array([10,1,20])

In [0]:
b=np.array([2,3,20])

In [69]:
a > b

array([ True, False, False])

In [71]:
np.nonzero(a>b)

(array([0]),)

In [0]:
## FANCING INDEXING IN 2-D

In [0]:
a = np.arange(0,36).reshape(6,6)

In [78]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [80]:
a[[0,1,2,3,4],
 [1,2,3,4,5]]     # To get diagonal elements. Same applies other highr dimesnions as well. Taking each square bracket as coordinate

array([ 1,  8, 15, 22, 29])

In [81]:
a[3:,[0,2,5]]

array([[18, 20, 23],
       [24, 26, 29],
       [30, 32, 35]])

In [82]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [0]:
mask = np.array([1,0,1,0,0,1], dtype=bool)

In [84]:
a[mask,2]

array([ 2, 14, 32])

In [0]:
# UNLIKE SLICING, FANCY INDEXING CREATES COPIES INSTEAD OF A VIEW INTO ORIGINAL ARRAY. WILL BE SHOWN THE SAME IN THE BELOW CODE SNIPPET

In [0]:
a = np.array([10,1,20])

In [0]:
subset = a[[0,2]]

In [89]:
subset

array([10, 20])

In [90]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [91]:
subset.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [92]:
a is subset

False

In [93]:
a

array([10,  1, 20])

In [94]:
subset

array([10, 20])

In [0]:
subset[0]=-1

In [96]:
subset

array([-1, 20])

In [97]:
a

array([10,  1, 20])

In [0]:
a = np.arange(25).reshape(5,5)

In [102]:
a[(a%3)==0] # To get all the elements divisible my 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [103]:
np.nan # not a number

nan

In [0]:
output = np.empty_like(a)

In [105]:
output

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0]])

In [0]:
output = np.empty_like(a)

In [107]:
output

array([[ 94725604336160, 140374615977920, 140375212411200,
        140374615939856, 140375211798616],
       [140374615977488, 140375212411200, 140374615999280,
        140375211798616, 140374616000816],
       [140375212411200, 140374616002064, 140375211798616,
        140374615940192, 140375212411200],
       [140374616001056, 140375211798616, 140374616001488,
        140375212411200, 140374616014992],
       [140375211798616, 140374616001248, 140375212411200,
        140374616578640, 140375212320728]])

In [0]:
a[(a%3)<> 0] = -1

In [114]:
a

array([[ 0, -1, -1,  3, -1],
       [-1,  6, -1, -1,  9],
       [-1, -1, 12, -1, -1],
       [15, -1, -1, 18, -1],
       [-1, 21, -1, -1, 24]])

In [116]:
np.where(a%3==0,a,np.nan)  #If there is nan, then array is floating point. Nan is floating point number that represents missing values

array([[ 0., nan, nan,  3., nan],
       [nan,  6., nan, nan,  9.],
       [nan, nan, 12., nan, nan],
       [15., nan, nan, 18., nan],
       [nan, 21., nan, nan, 24.]])