[View in Colaboratory](https://colab.research.google.com/github/kalyan369/Python_Practice/blob/master/AB_Numpy_Examples.ipynb)

In [0]:
import numpy as np

In [0]:
# SLICING IN NUMPY ARRAYS

In [0]:
a = np.array([10,11,12,13,14])

In [4]:
a[1:3] #same in python list, upper bound is not included--for 1D array same as python list

array([11, 12])

In [0]:
# Negative indices also works here

In [6]:
a[1:-2] # Think it as drop first element and drop last two elements

array([11, 12])

In [7]:
a[-4:3]

array([11, 12])

In [0]:
# Omitting indices

In [9]:
a[:3] #grab first three elements

array([10, 11, 12])

In [10]:
a[-2:] #grab last two elements

array([13, 14])

In [11]:
a[::2] # every second elemet

array([10, 12, 14])

In [0]:
a = np.array(list(range(25))).reshape(5,5)

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
a[0, 3:5]

array([3, 4])

In [15]:
a[4:,4:]

array([[24]])

In [16]:
a[:,2] #getting a column

array([ 2,  7, 12, 17, 22])

In [0]:
# Whenever we do index, we end up dropping a dimension. Slicing doesnt drop dimension

In [0]:
g = [1,2,3]

In [19]:
g[0] #Dropping a dimension when we are indexing as it just enter integer

1

In [20]:
g[0:1]

[1]

In [21]:
a[2::2, ::2]

array([[10, 12, 14],
       [20, 22, 24]])

In [0]:
b = np.arange(25).reshape(5,5)

In [23]:
b[4,:]

array([20, 21, 22, 23, 24])

In [24]:
b[:,1::2] # Everytime there is colon, then it is slicing

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [25]:
b[4]

array([20, 21, 22, 23, 24])

In [26]:
b[-1] #returns last row - 

array([20, 21, 22, 23, 24])

In [27]:
b[:,-1] #returns last column

array([ 4,  9, 14, 19, 24])

In [28]:
a[4,:] # a[-1,:] are advised as it indicates two dimensional

array([20, 21, 22, 23, 24])

In [30]:
a[1::2,:-1:2]

array([[ 5,  7],
       [15, 17]])

In [31]:
id(a)

140305047033696

In [34]:
a.flags # a disctionary which tells if the array owns the data

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [0]:
examp = np.array([1,2,3,4])

In [36]:
examp.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [37]:
examp.data # gives the pointer for the data

<read-write buffer for 0x7f9b50721da0, size 32, offset 0 at 0x7f9b5077e030>

In [0]:
c = examp.copy() # copies the entire data to another array

In [40]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False