[View in Colaboratory](https://colab.research.google.com/github/kalyan369/Python_Practice/blob/master/AB_Numpy_Examples_Fancy_Indexing.ipynb)

In [0]:
import numpy as np

In [27]:
a = np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [0]:
#Fancy indexing
indices = [1,2,-3]
y = a[indices]

In [29]:
y

array([10, 20, 50])

In [0]:
# Manual creation of masks
mask = np.array([0,1,1,0,0,1,0,1],dtype=bool) # numpy converts all 1s into True and 0s into False

In [0]:
# Conditional creation of masks
mask2 = a < 30

In [32]:
# fancy indexing
y = a[mask]
print(y)

[10 20 50 70]


In [33]:
# Applying mask2 on the numpy array
y = a[mask2]
y

array([ 0, 10, 20])

In [0]:
a = np.array([3,-1,-2,4,-6,8])

In [35]:
a < 0

array([False,  True,  True, False,  True, False])

In [0]:
negatives = a < 0

In [37]:
a[negatives] # returns all the negative values in the array

array([-1, -2, -6])

In [38]:
a[a<0] 

array([-1, -2, -6])

In [0]:
a[a<0] = 0 # assign 0 to all the negative values

In [40]:
a

array([3, 0, 0, 4, 0, 8])

In [41]:
a < 8

array([ True,  True,  True,  True,  True, False])

In [42]:
a >3

array([False, False, False,  True, False,  True])

In [0]:
# a > 3 and a < 8

In [44]:
(a<8).any() # returns true even if one of them is false

True

In [0]:
# & stands for and , | stands for or, ~ stands for not, and ^ stands for xor

In [0]:
# Binary operators (and, or,not) needs one true and one false each side

In [0]:
# Bitwise operators & (and) , | (or), ~ (not), ^ (xor)

In [0]:
# Biwise operators are for element wise operation

In [49]:
(a > 3) & (a < 8) # Brackets are used as bitwise operators has higher precedence over comparison operators

array([False, False, False,  True, False, False])

In [50]:
a

array([3, 0, 0, 4, 0, 8])

In [0]:
f=6
g=9

In [52]:
f+g

15

In [53]:
f.__add__(g) # __add__ is calld dunder similar to that athere are a.__abs__, a.__add__

15

In [0]:
#   OR TABLE
#   T  |  F
#T  T     F
#F  T     F
#

In [0]:
#   XOR TABLE
#   T  |  F
#T  F     T
#F  T     F
#