[View in Colaboratory](https://colab.research.google.com/github/kalyan369/Python_Practice/blob/master/AC_Numpy_Examples_Wind_Statistics.ipynb)

In [2]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.


In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

In [0]:
# drive/Python_Practice/Numpy-Tutorial-SciPyConf-2018-master/exercises/wind_statistics/

In [0]:
import numpy as np
from numpy import loadtxt

In [0]:
data = loadtxt('drive/Python_Practice/Numpy-Tutorial-SciPyConf-2018-master/exercises/wind_statistics/wind.data')

In [7]:
data.shape

(6574, 15)

In [0]:
#Taking out dates
dates = data[:,:3]

In [0]:
#Taking out winds data
winds = data[:,3:]

In [10]:
#Question:2
winds.mean()

10.22837377040868

In [11]:
winds.max()

42.54

In [12]:
winds.std()

5.603840181095793

In [0]:
#Question:3

In [14]:
winds.min(axis=0)

array([0.67, 0.21, 1.5 , 0.  , 0.13, 0.  , 0.  , 0.  , 0.  , 0.04, 0.13,
       0.67])

In [15]:
winds.max(axis=0)

array([35.8 , 33.37, 33.84, 28.46, 37.54, 26.16, 30.37, 31.08, 25.88,
       28.21, 42.38, 42.54])

In [16]:
winds.mean(axis=0)

array([12.36371463, 10.64644813, 11.66010344,  6.30627472, 10.45688013,
        7.09225434,  9.7968345 ,  8.49442044,  8.49581838,  8.70726803,
       13.121007  , 15.59946152])

In [17]:
winds.std(axis=0)

array([5.61918301, 5.26820081, 5.00738377, 3.60513309, 4.93536333,
       3.96838126, 4.97689374, 4.49865783, 4.16746101, 4.50327222,
       5.83459319, 6.69734719])

In [0]:
#Question: 4

In [19]:
winds.min(axis=1)

array([9.29, 6.5 , 6.17, ..., 8.71, 9.13, 9.59])

In [21]:
winds.max(axis=1)

array([18.5 , 17.54, 18.5 , ..., 29.58, 28.79, 27.29])

In [22]:
winds.mean(axis=1)

array([13.09666667, 11.79833333, 11.34166667, ..., 14.89      ,
       15.3675    , 15.4025    ])

In [23]:
winds.std(axis=1)

array([2.5773188 , 3.28972854, 3.50543348, ..., 5.51175108, 5.30456427,
       5.45971172])

In [0]:
# Question: 5

In [26]:
winds.argmax(axis=1)

array([10, 10,  0, ..., 11, 11,  2])

In [0]:
# Question 6

In [28]:
winds.max(axis=1).argmax()

2161

In [0]:
row = winds.max(axis=1).argmax()

In [30]:
dates[row]

array([66., 12.,  2.])

In [35]:
#OR
np.argmax(np.max(winds,axis=1))

2161

In [0]:
row = np.argmax(np.max(winds,axis=1))

In [37]:
dates[row]

array([66., 12.,  2.])

In [0]:
#OR
rows,cols=np.where(winds == winds.max())

In [0]:
#OR
rows,cols=np.nonzero(winds == winds.max())

In [0]:
#Question: 7

In [0]:
january = dates[:,1]==1

In [47]:
winds[january,:].mean(axis=0)

array([14.86955197, 12.92166667, 13.29962366,  7.19949821, 11.67571685,
        8.05483871, 11.81935484,  9.5094086 ,  9.54320789, 10.05356631,
       14.55051971, 18.02876344])